fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/ripienaar/puppet-concat.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    dell: "#{source_dir}"
