name         'gizmoguy-dell'
version      '0.0.0'
source       'https://github.com/gizmoguy/puppet-dell'
author       'gizmoguy'
license      'Apache License, Version 2.0'
summary      'Puppet module for managing Dell machines'
description  'Puppet module for managing Dell OMSA and other useful things on Dell hardware'
project_page 'https://github.com/gizmoguy/puppet-dell'
